[manager]
prepend_keymap = [
  { on = [ "1" ], run = "plugin relative-motions 1", desc = "Move in relative steps" },
  { on = [ "2" ], run = "plugin relative-motions 2", desc = "Move in relative steps" },
  { on = [ "3" ], run = "plugin relative-motions 3", desc = "Move in relative steps" },
  { on = [ "4" ], run = "plugin relative-motions 4", desc = "Move in relative steps" },
  { on = [ "5" ], run = "plugin relative-motions 5", desc = "Move in relative steps" },
  { on = [ "6" ], run = "plugin relative-motions 6", desc = "Move in relative steps" },
  { on = [ "7" ], run = "plugin relative-motions 7", desc = "Move in relative steps" },
  { on = [ "8" ], run = "plugin relative-motions 8", desc = "Move in relative steps" },
  { on = [ "9" ], run = "plugin relative-motions 9", desc = "Move in relative steps" },
  { on = [ "!" ], run = 'shell "$SHELL" --block --confirm', desc = "Open shell here" },
  { on = [ "E" ], run = "plugin eza-preview",  desc = "Toggle tree/list dir preview" },
  { on = [ "-" ], run = "plugin eza-preview inc_level", desc = "Increment tree level" },
  { on = [ "_" ], run = "plugin eza-preview dec_level", desc = "Decrement tree level" },
  { on = [ "$" ], run = "plugin eza-preview toggle_follow_symlinks", desc = "Toggle tree follow symlinks" },
  { on = [ "g", "i" ], run = "plugin lazygit", desc = "run lazygit" },
  { on = [ "T", "h" ], run = "plugin toggle-pane min-parent", desc = "Show/hide the parent pane" },
  { on = [ "T", "T" ], run = "plugin toggle-pane min-current", desc = "Show/hide the current pane" },
  { on = [ "T", "l" ], run = "plugin toggle-pane min-preview", desc = "Show/hide the preview pane" }
]

